import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import net from 'node:net';
const root=process.cwd(); const directory=mkdtempSync(path.join(os.tmpdir(),'v79-academy-test-'));
const socket=net.createServer(); await new Promise(r=>socket.listen(0,'127.0.0.1',r)); const port=socket.address().port;await new Promise(r=>socket.close(r));
const child=spawn(process.execPath,[path.join(root,'dist/server.cjs')],{cwd:directory,env:{...process.env,NODE_ENV:'production',PORT:String(port),ADMIN_PASSWORD:'isolated-test-password-123'},stdio:'ignore'});
const base=`http://127.0.0.1:${port}`;
async function api(route,{method='GET',cookie='',body,status=200,headers={}}={}) {
  const response=await fetch(base+route,{method,headers:{...(cookie?{Cookie:cookie}:{}),...headers,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
  const data=await response.json();assert.equal(response.status,status,`${method} ${route}: ${JSON.stringify(data)}`);return {data,cookie:response.headers.get('set-cookie')?.split(';')[0]};
}
try {
  for(let i=0;i<100;i++){try{await fetch(base+'/api/learner/session');break;}catch{await new Promise(r=>setTimeout(r,100));}}
  const guest=await api('/api/learner/session');assert.equal(guest.data.user,null);
  const catalog=(await api('/api/public/courses')).data;assert.ok(catalog.length>=2);assert.ok(catalog.every(c=>!c.programme));
  await api('/api/courses',{status:401});
  const login=await api('/api/admin/login',{method:'POST',body:{password:'isolated-test-password-123'}});
  const changed=await api('/api/admin/change-password',{method:'POST',cookie:login.cookie,body:{currentPassword:'isolated-test-password-123',newPassword:'updated-test-password-456'}});
  const admin=changed.cookie || (await api('/api/admin/login',{method:'POST',body:{password:'updated-test-password-456'}})).cookie;
  const free=catalog[0];
  const freeModules=(await api(`/api/public/courses/${free.id}/modules`)).data;
  const freeLessons=(await api(`/api/public/modules/${freeModules[0].id}/lessons`)).data;
  assert.ok(freeLessons[0].lessonContent);
  const account=await api('/api/learner/register',{method:'POST',body:{email:'learner@example.test',name:'Test Learner',password:'learner-password-123'}});const learner=account.cookie;
  await api('/api/learner/login',{method:'POST',body:{email:'learner@example.test',password:'incorrect-password'},status:401});
  await api(`/api/learner/enroll/${free.id}`,{method:'POST',cookie:learner});
  await api(`/api/learner/progress/${free.id}`,{method:'PUT',cookie:learner,body:{completedLessons:{[freeLessons[0].id]:true,'foreign-lesson':true},programmeState:{examAttempts:[{passed:true,score:100}],certificateId:'FAKE'}}});
  const progress=(await api(`/api/learner/progress/${free.id}`,{cookie:learner})).data;
  assert.equal(progress.completedLessons['foreign-lesson'],undefined);assert.equal(progress.programmeState.examAttempts.length,0);assert.equal(progress.programmeState.certificateId,undefined);
  await api(`/api/learner/certificate/${free.id}`,{method:'POST',cookie:learner,status:409});
  const source = JSON.parse(readFileSync(path.join(directory,'data/store.json'),'utf8'));
  const programme = source.courses.find(c=>c.programme);
  const publicProgramme = (await api(`/api/public/courses/by-slug/${programme.id}`)).data;
  assert.ok(publicProgramme.programme.finalExam.questions.every(q=>q.correctAnswer===''));
  await api(`/api/learner/exam/${programme.id}`,{method:'POST',cookie:learner,body:{answers:{}},status:409});
  const lessons = source.lessons.filter(l=>l.courseId===programme.id);
  const assignments = source.assignments.filter(a=>a.courseId===programme.id);
  await api(`/api/learner/progress/${programme.id}`,{method:'PUT',cookie:learner,body:{completedLessons:Object.fromEntries(lessons.map(l=>[l.id,true])),assignmentSubmissions:Object.fromEntries(assignments.map(a=>[a.id,{text:'Completed practical activity response'}]))}});
  const quiz=source.quizzes.find(q=>lessons.some(l=>l.id===q.lessonId));
  const publicQuiz=(await api(`/api/public/lessons/${quiz.lessonId}/quiz`)).data;
  assert.ok(publicQuiz.questions.every(q=>q.correctAnswer===undefined));
  const quizResult=(await api(`/api/public/lessons/${quiz.lessonId}/quiz/submit`,{method:'POST',body:{answers:Object.fromEntries(quiz.questions.map(q=>[q.id,typeof q.correctAnswer==='number'?q.options[q.correctAnswer]:q.correctAnswer]))}})).data;
  assert.equal(quizResult.score,100);
  const passed=(await api(`/api/learner/exam/${programme.id}`,{method:'POST',cookie:learner,body:{answers:Object.fromEntries(programme.programme.finalExam.questions.map(q=>[q.id,q.correctAnswer]))}})).data;
  assert.equal(passed.attempt.score,100);
  const certificate=(await api(`/api/learner/certificate/${programme.id}`,{method:'POST',cookie:learner})).data;
  assert.equal(certificate.name,'Test Learner'); assert.ok(certificate.id.startsWith('V79-'));
  const premium=(await api('/api/courses',{method:'POST',cookie:admin,status:201,body:{title:'Subscription test',status:'Published',pricingType:'subscription',category:'Test Application'}})).data;
  const mod=(await api(`/api/courses/${premium.id}/modules`,{method:'POST',cookie:admin,status:201,body:{title:'Module'}})).data;
  const lesson=(await api(`/api/modules/${mod.id}/lessons`,{method:'POST',cookie:admin,status:201,body:{title:'Welcome',lessonContent:'PROTECTED_CONTENT'}})).data;
  const locked=(await api(`/api/public/modules/${mod.id}/lessons`)).data;
  assert.equal(locked[0].lessonContent,undefined);assert.equal(locked[0].locked,true);
  await api(`/api/public/lessons/${lesson.id}/content-blocks`,{status:403});
  await api(`/api/public/courses/${premium.id}/assignments`,{status:403});
  await api(`/api/learner/enroll/${premium.id}`,{method:'POST',cookie:learner,status:403});
  await api('/api/learner/checkout',{method:'POST',cookie:learner,status:503});
  await api(`/api/learners/${account.data.user.id}/membership`,{method:'PUT',cookie:admin,body:{status:'active',expiresAt:'2000-01-01'},status:400});
  await api(`/api/learners/${account.data.user.id}/membership`,{method:'PUT',cookie:admin,body:{status:'active',expiresAt:new Date(Date.now()+86400000).toISOString()}});
  await api(`/api/learner/enroll/${premium.id}`,{method:'POST',cookie:learner});
  assert.equal((await api(`/api/public/modules/${mod.id}/lessons`,{cookie:learner})).data[0].lessonContent,'PROTECTED_CONTENT');
  await api(`/api/learners/${account.data.user.id}/membership`,{method:'PUT',cookie:admin,body:{status:'inactive'}});
  await api(`/api/public/lessons/${lesson.id}/quiz`,{cookie:learner,status:403});
  await api(`/api/courses/${premium.id}`,{method:'DELETE',cookie:admin});
  await api(`/api/public/courses/by-slug/${premium.id}`,{status:404});
  const stored=JSON.parse(readFileSync(path.join(directory,'data/store.json'),'utf8'));
  assert.equal(stored.modules.some(m=>m.courseId===premium.id),false);assert.equal(stored.lessons.some(l=>l.courseId===premium.id),false);
  await api('/api/admin/reset-password',{method:'POST',body:{token:'V79-RECOVERY-KEY-2026',newPassword:'replacement-password'},status:401});
  const recovery=(await api('/api/admin/recovery-info')).data;assert.equal(JSON.stringify(recovery).includes('V79-RECOVERY-KEY-2026'),false);
  await api('/api/learner/logout',{method:'POST',cookie:learner});await api(`/api/learner/progress/${free.id}`,{cookie:learner,status:401});
  console.log('✓ Academy API: accounts, enrolment, protected content, membership grant/revoke/expiry, progress validation, certificate checks, deletion, recovery and logout passed');
} finally {child.kill();await new Promise(r=>child.once('exit',r));rmSync(directory,{recursive:true,force:true});}
